package org.travel.entities;
// Generated 19 nov. 2017 18:26:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Commentaireoffre generated by hbm2java
 */
public class Commentaireoffre  implements java.io.Serializable {


     private int idComoffre;
     private String texte;
     private Date created;
     private Integer offreId;
     private Integer voyageurId;

    public Commentaireoffre() {
    }

	
    public Commentaireoffre(int idComoffre) {
        this.idComoffre = idComoffre;
    }
    public Commentaireoffre(int idComoffre, String texte, Date created, Integer offreId, Integer voyageurId) {
       this.idComoffre = idComoffre;
       this.texte = texte;
       this.created = created;
       this.offreId = offreId;
       this.voyageurId = voyageurId;
    }
   
    public int getIdComoffre() {
        return this.idComoffre;
    }
    
    public void setIdComoffre(int idComoffre) {
        this.idComoffre = idComoffre;
    }
    public String getTexte() {
        return this.texte;
    }
    
    public void setTexte(String texte) {
        this.texte = texte;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Integer getOffreId() {
        return this.offreId;
    }
    
    public void setOffreId(Integer offreId) {
        this.offreId = offreId;
    }
    public Integer getVoyageurId() {
        return this.voyageurId;
    }
    
    public void setVoyageurId(Integer voyageurId) {
        this.voyageurId = voyageurId;
    }




}


