package org.travel.entities;
// Generated 19 nov. 2017 18:26:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Commentaireblog generated by hbm2java
 */
public class Commentaireblog  implements java.io.Serializable {


     private int idComblog;
     private String texte;
     private Date created;
     private Integer articleId;
     private Integer voyageurId;

    public Commentaireblog() {
    }

	
    public Commentaireblog(int idComblog) {
        this.idComblog = idComblog;
    }
    public Commentaireblog(int idComblog, String texte, Date created, Integer articleId, Integer voyageurId) {
       this.idComblog = idComblog;
       this.texte = texte;
       this.created = created;
       this.articleId = articleId;
       this.voyageurId = voyageurId;
    }
   
    public int getIdComblog() {
        return this.idComblog;
    }
    
    public void setIdComblog(int idComblog) {
        this.idComblog = idComblog;
    }
    public String getTexte() {
        return this.texte;
    }
    
    public void setTexte(String texte) {
        this.texte = texte;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Integer getArticleId() {
        return this.articleId;
    }
    
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }
    public Integer getVoyageurId() {
        return this.voyageurId;
    }
    
    public void setVoyageurId(Integer voyageurId) {
        this.voyageurId = voyageurId;
    }




}


