package org.travel.entities;
// Generated 19 nov. 2017 18:26:39 by Hibernate Tools 4.3.1



/**
 * Image generated by hbm2java
 */
public class Image  implements java.io.Serializable {


     private int idImage;
     private String chemin;
     private Integer offreId;

    public Image() {
    }

	
    public Image(int idImage) {
        this.idImage = idImage;
    }
    public Image(int idImage, String chemin, Integer offreId) {
       this.idImage = idImage;
       this.chemin = chemin;
       this.offreId = offreId;
    }
   
    public int getIdImage() {
        return this.idImage;
    }
    
    public void setIdImage(int idImage) {
        this.idImage = idImage;
    }
    public String getChemin() {
        return this.chemin;
    }
    
    public void setChemin(String chemin) {
        this.chemin = chemin;
    }
    public Integer getOffreId() {
        return this.offreId;
    }
    
    public void setOffreId(Integer offreId) {
        this.offreId = offreId;
    }




}


