package org.travel.entities;
// Generated 19 nov. 2017 18:26:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Participation generated by hbm2java
 */
public class Participation  implements java.io.Serializable {


     private int idParticipation;
     private String message;
     private Date created;
     private Integer offreId;
     private Integer voyageurId;

    public Participation() {
    }

	
    public Participation(int idParticipation) {
        this.idParticipation = idParticipation;
    }
    public Participation(int idParticipation, String message, Date created, Integer offreId, Integer voyageurId) {
       this.idParticipation = idParticipation;
       this.message = message;
       this.created = created;
       this.offreId = offreId;
       this.voyageurId = voyageurId;
    }
   
    public int getIdParticipation() {
        return this.idParticipation;
    }
    
    public void setIdParticipation(int idParticipation) {
        this.idParticipation = idParticipation;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Integer getOffreId() {
        return this.offreId;
    }
    
    public void setOffreId(Integer offreId) {
        this.offreId = offreId;
    }
    public Integer getVoyageurId() {
        return this.voyageurId;
    }
    
    public void setVoyageurId(Integer voyageurId) {
        this.voyageurId = voyageurId;
    }




}


