package org.travel.entities;
// Generated 19 nov. 2017 18:26:39 by Hibernate Tools 4.3.1



/**
 * Souvenir generated by hbm2java
 */
public class Souvenir  implements java.io.Serializable {


     private int idSouvenir;
     private String description;
     private String image;
     private Integer voyageurId;

    public Souvenir() {
    }

	
    public Souvenir(int idSouvenir) {
        this.idSouvenir = idSouvenir;
    }
    public Souvenir(int idSouvenir, String description, String image, Integer voyageurId) {
       this.idSouvenir = idSouvenir;
       this.description = description;
       this.image = image;
       this.voyageurId = voyageurId;
    }
   
    public int getIdSouvenir() {
        return this.idSouvenir;
    }
    
    public void setIdSouvenir(int idSouvenir) {
        this.idSouvenir = idSouvenir;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Integer getVoyageurId() {
        return this.voyageurId;
    }
    
    public void setVoyageurId(Integer voyageurId) {
        this.voyageurId = voyageurId;
    }




}


