package org.travel.entities;
// Generated 19 nov. 2017 18:26:39 by Hibernate Tools 4.3.1



/**
 * Typevoyage generated by hbm2java
 */
public class Typevoyage  implements java.io.Serializable {


     private int idType;
     private String nom;

    public Typevoyage() {
    }

	
    public Typevoyage(int idType) {
        this.idType = idType;
    }
    public Typevoyage(int idType, String nom) {
       this.idType = idType;
       this.nom = nom;
    }
   
    public int getIdType() {
        return this.idType;
    }
    
    public void setIdType(int idType) {
        this.idType = idType;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }




}


