package org.travel.entities;
// Generated 19 nov. 2017 18:26:39 by Hibernate Tools 4.3.1



/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private int idUser;
     private String email;
     private String password;
     private String nom;
     private String prenom;

    public Utilisateur() {
    }

	
    public Utilisateur(int idUser) {
        this.idUser = idUser;
    }
    public Utilisateur(int idUser, String email, String password, String nom, String prenom) {
       this.idUser = idUser;
       this.email = email;
       this.password = password;
       this.nom = nom;
       this.prenom = prenom;
    }
   
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }




}


