package org.travel.entities;
// Generated 19 nov. 2017 18:26:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Voyageur generated by hbm2java
 */
public class Voyageur  implements java.io.Serializable {


     private int idVoyageur;
     private Date dateNaissance;
     private String ville;
     private String tel;
     private String job;
     private String interet;
     private String image;
     private Integer userId;

    public Voyageur() {
    }

	
    public Voyageur(int idVoyageur) {
        this.idVoyageur = idVoyageur;
    }
    public Voyageur(int idVoyageur, Date dateNaissance, String ville, String tel, String job, String interet, String image, Integer userId) {
       this.idVoyageur = idVoyageur;
       this.dateNaissance = dateNaissance;
       this.ville = ville;
       this.tel = tel;
       this.job = job;
       this.interet = interet;
       this.image = image;
       this.userId = userId;
    }
   
    public int getIdVoyageur() {
        return this.idVoyageur;
    }
    
    public void setIdVoyageur(int idVoyageur) {
        this.idVoyageur = idVoyageur;
    }
    public Date getDateNaissance() {
        return this.dateNaissance;
    }
    
    public void setDateNaissance(Date dateNaissance) {
        this.dateNaissance = dateNaissance;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }
    public String getInteret() {
        return this.interet;
    }
    
    public void setInteret(String interet) {
        this.interet = interet;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }




}


